spring:
  cloud:
    services:
      registrationMethod: router
  zipkin:
    baseUrl: "https://myzipkin.apps.sys.tas.tkgi.haas-451.pez.vmware.com/"
    sender:
      type: web
eureka:
  instance:
     nonSecurePort: 80
