spring:
  application:
     name: web-service
eureka:
  client:
    registerWithEureka: true
    registryFetchIntervalSeconds: 10
pivotal:
  summary:
    quotes: 1
    symbols:
      it: PVTL
      fs: JPM

#ORCL,IBM,INTC,AMD,HPQ,CSCO,AAPL,
#JPM,C,MS,BAC,GS,WFC,BK
