spring:
  application:
     name: web-service
  zipkin:
    baseUrl: "https://myzipkin.apps.sys.tas.tkgi.haas-451.pez.vmware.com/"
eureka:
  instance:
    hostname: web-service.apps.sys.tas.tkgi.haas-451.pez.vmware.com
    nonSecurePortEnabled: false
    securePortEnabled: true
    secure-port: 443
  client:
    serviceUrl:
      defaultZone: https://eurekaserver.apps.sys.tas.tkgi.haas-451.pez.vmware.com//eureka/
    registerWithEureka: true
    registryFetchIntervalSeconds: 10
pivotal:
  summary:
    quotes: 3
    symbols:
      it: ORCL,IBM,INTC,AMD,HPQ,CSCO,AAPL,PVTL
      fs: JPM,C,MS,BAC,GS,WFC,BK
