spring:
  application:
     name: zipkin-service
security:
  basic:
    enabled: false
eureka:
  instance:
    hostname: zipkin-service.apps.sys.tas.tkgi.haas-451.pez.vmware.com
    nonSecurePortEnabled: false
    securePortEnabled: true
    secure-port: 443
  client:
    serviceUrl:
      defaultZone: https://eurekaserver.apps.sys.tas.tkgi.haas-451.pez.vmware.com//eureka/
    registerWithEureka: true
    registryFetchIntervalSeconds: 10
